"""Fix backref car

Revision ID: 17f54d0c92e4
Revises: 
Create Date: 2022-08-12 21:35:38.061057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f54d0c92e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.create_unique_constraint(None, 'users', ['first_name'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['last_name'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
